# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_cardtest',
                'doc_host': 'https://adamcc.github.io',
                'git_url': 'https://github.com/adamcc/nbdev_cardtest',
                'lib_path': 'nbdev_cardtest'},
  'syms': {'nbdev_cardtest.core': {'nbdev_cardtest.core.foo': ('core.html#foo', 'nbdev_cardtest/core.py')}}}